import { useEffect, useState } from 'react';
import { Settings2, X } from 'lucide-react';

const SESSION_KEY='jobradar.supabase.session';
function token(){try{return (JSON.parse(sessionStorage.getItem(SESSION_KEY)||'{}') as {access_token?:string}).access_token||''}catch{return ''}}
async function api<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Authorization',`Bearer ${token()}`);headers.set('Content-Type','application/json');const r=await fetch(`/api${path}`,{...init,headers});if(!r.ok)throw new Error(await r.text()||`Request failed (${r.status})`);return r.status===204?undefined as T:await r.json()}

type Settings={showNotifications:boolean;showMatching:boolean};
export default function AdminControls(){
 const [open,setOpen]=useState(false);const [s,setS]=useState<Settings>({showNotifications:false,showMatching:false});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{api<Settings>('/workspace/settings').then(setS).catch(()=>{})},[]);
 const save=async(next:Settings)=>{setBusy(true);setMessage('');try{const v=await api<Settings>('/workspace/settings',{method:'PUT',body:JSON.stringify(next)});setS(v);setMessage('Saved for all users.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}};
 return <><button onClick={()=>setOpen(true)} className="fixed bottom-4 left-4 z-40 inline-flex items-center gap-2 rounded-lg border bg-background px-3 py-2 text-xs font-semibold shadow-lg hover:bg-muted"><Settings2 size={15}/>Admin workspace</button>{open&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/30 p-4 sm:items-center"><div className="w-full max-w-md rounded-2xl border bg-card p-5 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">Admin</p><h2 className="mt-1 text-lg font-bold">User workspace visibility</h2></div><button onClick={()=>setOpen(false)} className="rounded-lg p-2 hover:bg-muted"><X size={18}/></button></div><p className="mt-2 text-sm text-muted-foreground">Core pages stay visible. Toggle optional modules for all users.</p><div className="mt-5 space-y-2">{[['showNotifications','Notifications','Show the alert history page'],['showMatching','Matching','Show scoring details']].map(([key,label,detail])=><label key={key} className="flex cursor-pointer items-center justify-between rounded-xl border p-4"><span><span className="block text-sm font-semibold">{label}</span><span className="block text-xs text-muted-foreground">{detail}</span></span><input type="checkbox" checked={(s as any)[key]} disabled={busy} onChange={e=>save({...s,[key]:e.target.checked})} className="h-4 w-4"/></label>)}</div>{message&&<p className="mt-4 rounded-lg bg-secondary px-3 py-2 text-xs">{message}</p>}<div className="mt-5 text-xs text-muted-foreground">Users always get Today, Jobs, Applications and Profile.</div></div></div>}</>;
}
