import { useEffect, useState } from 'react';
import { Settings2, X } from 'lucide-react';
import App from './App';

const SESSION_KEY='jobradar.supabase.session';
const API_BASE=((import.meta.env.VITE_API_URL as string|undefined)?.trim()||'https://job-radar-nfgv.onrender.com').replace(/\/+$/,'');
function token(){try{return (JSON.parse(sessionStorage.getItem(SESSION_KEY)||'{}') as {access_token?:string}).access_token||''}catch{return ''}}
async function api<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Authorization',`Bearer ${token()}`);headers.set('Content-Type','application/json');const r=await fetch(`${API_BASE}/api${path}`,{...init,headers});if(!r.ok)throw new Error(await r.text()||`Request failed (${r.status})`);return r.status===204?undefined as T:await r.json()}

type Me={role:string};
type Settings={showNotifications:boolean;showMatching:boolean};
export default function AdminControls(){
 const [me,setMe]=useState<Me|null>(null);const [roleLoading,setRoleLoading]=useState(true);
 const [open,setOpen]=useState(false);const [adminOpen,setAdminOpen]=useState(false);const [s,setS]=useState<Settings>({showNotifications:false,showMatching:false});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{api<Me>('/auth/me').then(setMe).catch(()=>setMe(null)).finally(()=>setRoleLoading(false))},[]);
 useEffect(()=>{if(me?.role==='ADMIN')api<Settings>('/workspace/settings').then(setS).catch(()=>{})},[me?.role]);
 if(roleLoading||me?.role!=='ADMIN')return null;
 const save=async(next:Settings)=>{setBusy(true);setMessage('');try{const v=await api<Settings>('/workspace/settings',{method:'PUT',body:JSON.stringify(next)});setS(v);setMessage('Saved for all users.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}};
 return <>{adminOpen&&<div className="fixed inset-0 z-[60] overflow-auto bg-background"><button type="button" onClick={()=>setAdminOpen(false)} aria-label="Exit admin console" className="fixed right-4 top-20 z-[70] inline-flex min-h-10 items-center gap-2 rounded-md border bg-card px-3 py-2 text-xs font-semibold shadow-md hover:bg-muted focus-visible:outline-2 focus-visible:outline-primary"><X size={15} aria-hidden="true"/>Exit admin console</button><App/></div>}<button type="button" onClick={()=>setOpen(true)} className="fixed bottom-4 left-4 z-40 inline-flex min-h-11 items-center gap-2 rounded-lg border bg-background px-3 py-2 text-xs font-semibold shadow-lg hover:bg-muted"><Settings2 size={15} aria-hidden="true"/>Admin workspace</button>{open&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/30 p-4 sm:items-center"><div className="w-full max-w-md rounded-2xl border bg-card p-5 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">Admin</p><h2 className="mt-1 text-lg font-bold">Admin workspace</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close admin workspace" className="rounded-lg p-2 hover:bg-muted"><X size={18} aria-hidden="true"/></button></div><p className="mt-2 text-sm text-muted-foreground">Every account uses the same Job Radar workspace. Admin-only tools are additive and are available only to administrators.</p><button onClick={()=>{setOpen(false);setAdminOpen(true)}} className="mt-5 w-full rounded-xl border bg-background p-4 text-left hover:bg-muted"><span className="block text-sm font-semibold">Open admin console</span><span className="mt-1 block text-xs text-muted-foreground">Manage companies, sources, scans, source health, and workspace controls.</span></button><div className="mt-5 space-y-2">{[['showNotifications','Notifications','Show the alert history page'],['showMatching','Matching','Show scoring details']].map(([key,label,detail])=><label key={key} className="flex cursor-pointer items-center justify-between rounded-xl border p-4"><span><span className="block text-sm font-semibold">{label}</span><span className="block text-xs text-muted-foreground">{detail}</span></span><input type="checkbox" checked={(s as any)[key]} disabled={busy} onChange={e=>save({...s,[key]:e.target.checked})} className="h-4 w-4"/></label>)}</div>{message&&<p className="mt-4 rounded-lg bg-secondary px-3 py-2 text-xs">{message}</p>}<div className="mt-5 text-xs text-muted-foreground">Admin = all user access + admin access.</div></div></div>}</>;
}
